### ISSUE TITLE
Wrong [66] reference 

### ISSUE THREAD

**Issue by jingtaozhan** [gimpong/WWW22-HCQ#1]
Hi, congratulations to your WWW22 paper!

This is a kind reminder of your [66] paper reference. I think the name of the cited paper is wrong. I assume you want to cite "Learning Discrete Representations via Constrained Clustering for Effective and Efficient Dense Retrieval", but the current name is the same as [65].

Maybe consider an update of the arxiv paper?

**Comment by gimpong** [comment]
Thanks for the reminder. We have updated the tex files on arXiv and ACM submission website. The replacement on arXiv is scheduled to be announced at Thu, 10 Feb 2022 01:00:00 GMT. :)
